### ISSUE TITLE
Theme broken for PHP v8

### ISSUE THREAD

**Issue by trevorjwood** [triopsi/ice-cold#4]
I've just tried this theme on a website that needs to move to PHP8 and it is broken.

PHP error message is

[07-Mar-2022 10:42:51 UTC] PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in *****\wp-content\themes\ice-cold\template-parts\page\content-front-page.php:53
Stack trace:
#0 *****\wp-content\themes\ice-cold\template-parts\page\content-front-page.php(53): sprintf('Continue readin...', '<i class="fas f...')
#1 *****\wp-includes\template.php(772): require('C:\\websites\\lei...')
#2 *****\wp-includes\template.php(716): load_template('C:\\websites\\lei...', false, Array)
#3 *****\wp-includes\general-template.php(204): locate_template(Array, true, false, Array)
#4 *****\wp-content\themes\ice-cold\front-page.php(41): get_template_part('template-parts/...', 'front-page')
#5 *****\wp-includes\template-loader.php(106): include('C:\\websites\\lei...')
#6 *****\wp-blog-header.php(19): require_once('C:\\websites\\lei...')
#7 *****\index.php(17): require('C:\\websites\\lei...')
#8 {main}
  thrown in *****\wp-content\themes\ice-cold\template-parts\page\content-front-page.php on line 53

**Comment by trevorjwood** [comment]
I have some further information on this. When running under PHP 8, everything between the end of "Posts page" and "Blog/Site page layout" is missing under "Appearance/customise/home page settings"

**Comment by triopsi** [comment]
The topic will be updated soon. Thank you for reporting.
